### PR TITLE
[WIP] add `--with-vtest` to `vrecord`

### PR DESCRIPTION
**Pull request by retokromer**
## Work in Progress
- The PR https://github.com/amiaopensource/vrecord/pull/324 must be merged before this one.
- A new built must be made (and, of course, `url`, `version` and `sha256` must be updated in this PR) before merging.

This gives to the user the possibility to choose if she or he wishes to install the `vtest` tool or not.

### CODE REVIEW

**Comment by dericed** [comment]
This PR shouldn't have be okayed, there's no revision to it. I'm going to recall it from master.

**Comment by retokromer** [comment]
Sorry @aeschweik, this is still WIP and cannot be merged as it is, therefore I revert it.

**Comment by dericed** [comment]
This merged commit was dropped from master.

**Comment by aeschweik** [comment]
Oh no! Sorry, this was all me on autopilot. Thanks for fixing my mistake.

**Pull request merged**
