### PR TITLE
fixes for gtkdialog installs

### PR DESCRIPTION
**Pull request by dericed**
resolves https://github.com/amiaopensource/vrecord/issues/735

### CODE REVIEW

**Review by retokromer — APPROVED** [review]
Successfully tested on MacOS 10.14.6, 10.15.7 and 12.6.5, as well as on Ubuntu 22.04.2 LTS, but I could not reproduce the issue on my end.

**Comment by retokromer** [comment]
Thank you, @dericed !

**Comment by dericed** [comment]
Hi @retokromer, I'm guessing the issue pertains to xcode 14.3 or later if any of your setups have that, then I think gtkdialog.rb would fail without this patch. xcode 14.3 seemed to be common between myself, @arnicholson, @libbyhopfauf.

**Comment by retokromer** [comment]
@dericed You are right: I just checked and I was running Xcode 11.3.1 and 14.2 respectively. Thanks for the hint!

**Pull request merged**
