### PR TITLE
gtkdialog: upgrade to 0.8.5

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by dericed** [comment]
@retokromer does this pr work for you?

**Comment by dericed** [comment]
For me, this PR fails at make:

```
$ brew install gtkdialog.rb 
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 4.0.14 (72bdefb81) to 4.0.15 (0841d1a25).
Updated 5 taps (richardlehane/digipres, homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
ada-url                     ares                        chatblade                   git-big-picture             poke                        vulkan-validationlayers
amber                       ata                         ffmpeg@5                    millet                      vulkan-tools
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the mediamicroservices/mm tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/mediamicroservices/homebrew-mm/mm.rb:99


You have 20 outdated formulae and 12 outdated casks installed.


The 4.0.15 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.0.15
Error: Failed to load cask: gtkdialog.rb
Cask 'gtkdialog' is unreadable: wrong constant name #<Class:0x00007f7ee70ef868>
Warning: Treating gtkdialog.rb as a formula.
gtkdialog 0.8.4_4 is already installed but outdated (so it will be upgraded).
==> Fetching gtkdialog
==> Downloading https://github.com/puppylinux-woof-CE/gtkdialog/archive/0.8.5.tar.gz
Already downloaded: /Users/daverice/Library/Caches/Homebrew/downloads/b6ace736cbd459121836dd42bb7b91ce31491d11a3a45f48d51f4eb2810a3cbf--gtkdialog-0.8.5.tar.gz
==> Upgrading gtkdialog
  0.8.4_4 -> 0.8.5 

==> ./autogen.sh
==> make
Last 15 lines from /Users/daverice/Library/Logs/Homebrew/gtkdialog/02.make:
make[3]: *** [variables.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/stack.Tpo .deps/stack.Po
mv -f .deps/attributes.Tpo .deps/attributes.Po
mv -f .deps/gtkdialog.Tpo .deps/gtkdialog.Po
mv -f .deps/gtkdialog_parser.Tpo .deps/gtkdialog_parser.Po
mv -f .deps/automaton.Tpo .deps/automaton.Po
signals.c:1258:4: error: void function 'on_any_widget_auto_refresh_event' should not return a value [-Wreturn-type]
                        return FALSE;
                        ^      ~~~~~
1 error generated.
make[3]: *** [signals.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
```

I retested on the main branch and 0.8.4 installed okay for me.

Are the dependencies different for this version.

On your side does the gui appear or function differently under 0.8.5?

**Comment by retokromer** [comment]
Thank you, @dericed, for reporting! I can delve into this only in a few days, as I don’t have with me a “clean” computer to test with. As said, the 0.8.4 was working for me as well: I could not reproduce the issue on Intel nor on AArch64 on my end.

**Comment by dericed** [comment]
@privatezero does this PR work for you? I've tried a few different computers and while it does work for Reto, I can't get this to successfully build anywhere. Last error output was:

```
$ brew install gtkdialog.rb 
Error: Failed to load cask: gtkdialog.rb
Cask 'gtkdialog' is unreadable: wrong constant name #<Class:0x000000012a1066b8>
Warning: Treating gtkdialog.rb as a formula.
gtkdialog 0.8.4_3 is already installed but outdated (so it will be upgraded).
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> Fetching gtkdialog
==> Downloading https://github.com/puppylinux-woof-CE/gtkdialog/archive/0.8.5.ta
==> Downloading from https://codeload.github.com/puppylinux-woof-CE/gtkdialog/ta
##=#=-#                                                                        
==> Upgrading gtkdialog
  0.8.4_3 -> 0.8.5 

==> ./autogen.sh
==> make
Last 15 lines from /Users/drice/Library/Logs/Homebrew/gtkdialog/02.make:
                ^
automaton.c:359:3: note: did you mean 'instruction_execute_push'?
automaton.c:103:1: note: 'instruction_execute_push' declared here
instruction_execute_push(token Token, 
^
17 errors generated.
make[3]: *** [gtkdialog_parser.o] Error 1
automaton.c:996:4: error: call to undeclared function 'push_widget'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        push_widget(Widget, Widget_Type);
                        ^
3 errors generated.
make[3]: *** [automaton.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
```.

**Comment by dericed** [comment]
I know you closed this, but wanted to mentioned that when I applied this patch to my 0.8.4 update I still had the same make errors. Did you find any ui differences when you ran vrecord with gtkdialog 0.8.5?

**Comment by retokromer** [comment]
If I remember carefully nothing relevant, but I can check more carefully on Tuesday.

**Comment by privatezero** [comment]
@dericed I've been away from a computer traveling all week so haven't had a chance to test any of the patches - but it looks like your fix in https://github.com/amiaopensource/homebrew-amiaos/pull/354#issuecomment-1528846676 did the trick! I can give things a test on Monday on my end.

**Pull request closed without merging**
