### PR TITLE
0.8-1 is causing brew errors, reverting to 0.8

### PR DESCRIPTION
**Pull request by dericed**
contingent on https://travis-ci.org/bavc/qctools/builds/222560791 which is rerunning now

### CODE REVIEW

**Comment by retokromer** [comment]
Thank you! It works fine on my side on macOS, now trying Ubuntu.

You probably know this (on a fresh installation):
```
🍺  /usr/local/Cellar/qctools/0.8_2: 10 files, 7.1MB, built in 1 minute 35 seconds
Warning: `brew linkapps` has been deprecated and will eventually be removed!

Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
bundles that can be relocated. Instead, please consider using `brew cask` and
migrate formulae using `.app`s to casks.
Linking: /usr/local/opt/qctools/QCTools.app
Linked 1 app to /Applications
```

**Comment by retokromer** [comment]
FYI: on Ubuntu:
- `qcli` seems to work fine, but at installation needs a fix on `qwt` (update the one for _1 to _4) and the `--env=std` flag on a dependency
- `qctools` fails: `qmake` cannot resolve an SDK Path for macOS [Perhaps I will try to delve into that later this week.]

**Comment by dericed** [comment]
The SDK path error is from qt requiring some environmental variables from XCode. This [answer](http://stackoverflow.com/questions/41513456/qt-5-7-xcode-8-1-os-x-el-captain-could-not-resolve-sdk-path-for-macosx) likely works on Mac, not sure how to fix in linux.

**Comment by retokromer** [comment]
Thanks! XCode is macOS specific. Yet I had a similar issue with SDK in the past and therefore I should find quickly the Graal.

**Pull request merged**
