### PR TITLE
Revert "FFmpeg 4.3.1 (#253)"

### PR DESCRIPTION
**Pull request by retokromer**
This reverts commit 874aa288d11b37211427e91c3eb9a8deea08f01d.
As requested in https://github.com/amiaopensource/homebrew-amiaos/issues/254.

### CODE REVIEW

**Comment by retokromer** [comment]
@privatezero This is the version you requested. Also FFmpeg 4.2.4, released on 2020–07–09.

**Comment by privatezero** [comment]
thanks @retokromer - I'll see if @dericed has any objections, and then we can merge I think. Would this require the addition of `revision 1` to trigger the downgrade for people who have already installed latest version?

**Comment by retokromer** [comment]
>Would this require the addition of revision 1 to trigger the downgrade for people who have already installed latest version?

To my knowledge no, but I will add: it does not hurt.

**Comment by privatezero** [comment]
@retokromer, @dericed has isolated the upstream issue in https://github.com/amiaopensource/vrecord/pull/569 - so I think we can close this for now (assuming no other reversions pop up)

**Pull request closed without merging**
