### PR TITLE
vrecord 2020-06-26

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by privatezero** [comment]
Hi @retokromer sorry - we had to delete release and update with new version number! We are going to make some linux specific modifications to install formula as well - stand by

**Comment by retokromer** [comment]
No problem, @privatezero, I will update as soon as you are ready.

**Comment by dericed** [comment]
This pr also is missing dependencies for the new release and doesn't install all the files from the repo that are needed.

**Comment by retokromer** [comment]
Closing in favour of https://github.com/amiaopensource/homebrew-amiaos/pull/248/files.

**Pull request closed without merging**
