### PR TITLE
delete qwt-qt5

### PR DESCRIPTION
**Pull request by retokromer**
Meant to resolve https://github.com/amiaopensource/homebrew-amiaos/issues/148

- detete qwt-qt5
- update documentation (_en passant_, also regarding vrecord using gtkdialog)

### CODE REVIEW

**Comment by retokromer** [comment]
conflict resolved

**Comment by retokromer** [comment]
ping @dericed

**Comment by dericed** [comment]
will merge.

**Comment by retokromer** [comment]
@dericed Is the `qwt-qt5 ` formula needed by `QCTools` and/or `qcli`? If so, I will add again it.

See: https://github.com/bavc/qctools/blob/master/Project/QtCreator/brew_build.md

**Comment by dericed** [comment]
Not needed, I'm late in either moving the installer or working around the need of it.

**Comment by retokromer** [comment]
Thank you! Then all is fine here.

**Pull request merged**
