### PR TITLE
Add check for Pashua on install

### PR DESCRIPTION
**Pull request by privatezero**
Will check if Pashua is installed via homebrew or if already is in the
applications folder.  If not found will attempt to install Pashua via
brew cask.

### CODE REVIEW

**Comment by retokromer** [comment]
Cosmetic: please indent always by 2.

**Comment by privatezero** [comment]
Ack! I didn't notice the different windows I was working in had tab settings set differently!  Is this more like it?

**Comment by retokromer** [comment]
I’ll try to test the installation, but I’m currently not on my test computer, only a shitty thing.

**Comment by retokromer** [comment]
I guess this is fine and resolves https://github.com/amiaopensource/homebrew-amiaos/pull/13.

**Comment by dericed** [comment]
LGTM, it seems to sneak by `brew audit`

**Comment by retokromer** [comment]
This is a big improvement! Thank you, @privatezero

**Pull request merged**
