### PR TITLE
ffmpeg + decklink

### PR DESCRIPTION
**Pull request by dericed**
A WIP to build ffmpeg with decklink. I’m skeptical that homebrew will accept this approach, also I think it may be preferable to avoid conflict with the official homebrew ffmpeg formula, so this renames the output to ffmpeg-dl.

### CODE REVIEW

**Comment by dericed** [comment]
ping to @kieranjol

**Comment by retokromer** [comment]
I have to delve into this, but at the first look I am skeptical about having two versions of FFmpeg that the end users have to manage. I fear this would be an additional complication, which could slow down the adoption of those open-source solutions.

**Comment by kieranjol** [comment]
I might not be able to try this until Tuesday but I think that it's really useful. I remember manually building ffmpeg with decklink to be quite tedious. Great to see that someone is hosting a newer version of the SDK as well..

**Comment by dericed** [comment]
Thanks @retokromer and @kieranjol for comments. I'm also in favor of updating the bmd sdk in amiaos but want to ensure that we do so in a way that follows the terms. As far as I can tell, the open licenses in the headers of the sdk files in the macadam repo allow us to copy it into the amiaos repo, could consider this in a subsequent pr.

**Comment by kieranjol** [comment]
Looking forward to testing this once this gets merged: https://github.com/Homebrew/homebrew-core/pull/19101

**Comment by retokromer** [comment]
@dericed openjpeg 2.3 has just been released.

**Pull request merged**
