### PR TITLE
depends on doxygen

### PR DESCRIPTION
**Pull request by retokromer**
If I am not completely wrong, the formulae:

- audiorecorder
- qcli
- vrecord

depends on `doxygen`. This is often already installed IRL, but I think it’s a good think the make sure it is.

### CODE REVIEW

**Comment by dericed** [comment]
why `qcli`?

**Comment by retokromer** [comment]
Does it really not use it?

**Comment by retokromer** [comment]
Probably also

- bmdtools

**Comment by privatezero** [comment]
is this for generating man pages?

**Comment by retokromer** [comment]
I’m trying to figure out. Possibly it’s related to `ffmpeg` – that’s my current feeling.

I’m noticing this by installing just one formula in a brand new test environment. (It’s still for the FIAF training in Bangkok in June for which I would like a package that works cross-platform in an easy way.)

**Comment by privatezero** [comment]
Interesting! So this is something that is problematic in windows on linux? Anyway - looks good to me! Yay for cross-platform!

**Comment by retokromer** [comment]
@privatezero I noticed it first on macOS.

**Comment by privatezero** [comment]
Oh interesting! I just noticed that the install on my work computer is indeed from homebrew and not preinstalled.

**Comment by retokromer** [comment]
@dericed Do you wish that I revert `qcli` in this PR?

**Comment by dericed** [comment]
I haven't really looked at it, but if it indeed requires doxygen, then feel free to merge.

**Comment by retokromer** [comment]
@dericed Thanks for the answer! I have a doubt: could the two lines https://github.com/amiaopensource/homebrew-amiaos/blob/31c1a6228580a4e64f535b980c135e81ab03f884/qcli.rb#L25-L26 not be replaced by following one?
```
bin.install "qcli"
```

**Comment by dericed** [comment]
Hi @retokromer, I apologize, I forgot that this qcli.rb is superseded by https://github.com/Homebrew/homebrew-core/blob/master/Formula/qcli.rb. Perhaps we should remove it.

**Comment by retokromer** [comment]
Indeed! I’ll remove it. It’s better in Homebrew.

**Comment by retokromer** [comment]
@privatezero In fact, it seems to be related to `openjpeg`. Therefore, if `ffmpeg` is installed without it, then `doxygen` should not be necessary.

**Comment by retokromer** [comment]
**Update:** This is actually a bug in Brew. I’ll revert here.

**Pull request merged**
