### PR TITLE
move Cable Bible to GitLab

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by retokromer** [comment]
I cannot request a review by @EG-tech

Should resolve https://github.com/amiaopensource/governance/issues/8.

**Comment by privatezero** [comment]
I never understand when Github will allow/not allow reviewers - I'll preemptively approve so it won't be blocked when @EG-tech takes a look

**Review by privatezero — APPROVED** [review]

**Comment by retokromer** [comment]
@privatezero Should I add a revision bump?

**Comment by privatezero** [comment]
Hi @retokromer, I suppose that makes sense!

**Comment by retokromer** [comment]
Hello @EG-tech 
I noticed that GitHub is still mentioned. I opened a PR on [GitLab](https://gitlab.com/EG-tech/cable-bible/-/merge_requests/1) to update it. If you merge it and make a new release, I am happy to update this PR for the formula.

**Comment by retokromer** [comment]
@EG-tech ping

**Pull request merged**
