### PR TITLE
add system check

### PR DESCRIPTION
**Pull request by privatezero**
Necessary for vrecord dependencies to be happy on linux

### CODE REVIEW

**Comment by dericed** [comment]
would if/else be more resilient than if/elsif?

**Comment by retokromer** [comment]
I suggest here as well: if Linux, else if macOS, else «System not supported.»

**Comment by privatezero** [comment]
Updated to add warning and options - works as expected on so far on my end (ubuntu)

**Comment by retokromer** [comment]
Sorry, I am not sure I understand the need of options here. For what situation is this useful? And what happens if I choose `--with-linux` on macOS or `--with-macOS` on Linux?

**Comment by privatezero** [comment]
Added options as a fail-safe to give the user the ultimate control in case of any unanticipated issues in the future. (I can't really imagine what they would be, but that I suppose is the nature of unanticipated). 

If you use the wrong flag for the system then it will install according to the the flag and FFmpeg won't like it when you try to compile against it (as was the case with the current form of the formula).

**Comment by retokromer** [comment]
>If you use the wrong flag for the system then it will install according to the the flag and FFmpeg won't like it when you try to compile against it (as was the case with the current form of the formula).

Therefore I would not include the possibility. Probably just not my cup of tea…

**Comment by privatezero** [comment]
Haha, yeah, I guess just a difference of preference - I tend to favor the option to override automatic systems just in case! In the past I have actually needed to compile FFmpeg on Linux while targeting the build at a non-Linux platform (helping out people who were having troubles compiling on their end) so I can see being able to easily install a dependency like this being useful in that situation. An edge case for sure though!

**Comment by retokromer** [comment]
>I guess just a difference of preference

Indeed! Merge it!

**Pull request merged**
