### PR TITLE
add additional gtkdialog build dependencies

### PR DESCRIPTION
**Pull request by dericed**
fixes https://github.com/amiaopensource/vrecord/issues/665, thx @bturkus

### CODE REVIEW

**Comment by retokromer** [comment]
@dericed You were quicker than me! I can test in a couple of hours (after cooking – and eating – dinner).

**Review by retokromer — APPROVED** [review]
I cannot test in the same setting at the moment (macOs 11.2.2 on Intel CPU), but seems file.

@bturkus : Could you possibly test on  your configuration as well? Thank you!

**Comment by retokromer** [comment]
Thank you @dericed and @EG-tech

**Comment by EG-tech** [comment]
Looks like this already got merged but just noting that these commits fixed the gtkdialog install issue for me on Mojave 10.4.6 👍

**Pull request merged**
