### PR TITLE
hotfix for the qctools hotfix

### PR DESCRIPTION
**Pull request by dericed**
Related to https://github.com/bavc/qctools/issues/356

### CODE REVIEW

**Comment by ablwr** [comment]
Oh yes.

**Comment by ablwr** [comment]
Any more secret fixes in the pipeline to hotfix the hotfix for the qctools hotfix?

**Comment by retokromer** [comment]
LGTM

**Comment by dericed** [comment]
@ablwr I really hope not.

**Comment by retokromer** [comment]
FYI: Has given
```
==> Upgrading 1 outdated package, with result:
amiaopensource/amiaos/qctools 0.8_1
==> Upgrading amiaopensource/amiaos/qctools 
==> Downloading https://github.com/bavc/qctools/archive/v0.8-1.tar.gz
Already downloaded: /Users/test/Library/Caches/Homebrew/qctools-0.8.tar.gz
Error: SHA256 mismatch
Expected: 53f79d2d379a39cb0b568958daa07e071117058f72ac24ad63a8a8cf7f55f1ef
Actual: ad8dc56465db2d03dd804ef0d322d04a24cd9bcd2daba95d7f2aca789cc8a6aa
Archive: /Users/test/Library/Caches/Homebrew/qctools-0.8.tar.gz
To retry an incomplete download, remove the file above.
```
and after
```
sudo rm /Users/test/Library/Caches/Homebrew/qctools-0.8.tar.gz
```
worked fine.

**Comment by retokromer** [comment]
No, sorry QCTools is fine, but qcli has given:
```
Warning: Skipping amiaopensource/amiaos/qcli: most recent version 0.1_1 not installed
```
Is that `0.1_1` correct? I mean: should it not read `0.8_1`?

**Comment by retokromer** [comment]
By modifying the `qcli` formula:
```
version "0.8"
revision 2
```
(and deleting the previous download) it works on my side.

**Comment by dericed** [comment]
I think that's workable for now. Soon we'll have 8.1.

**Pull request merged**
