### PR TITLE
ffmpegdecklink 4.2.3

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by retokromer** [comment]
Replaces https://github.com/amiaopensource/homebrew-amiaos/pull/240

**Comment by dericed** [comment]
Ah, thanks @retokromer. I didn't see https://github.com/amiaopensource/homebrew-amiaos/pull/240 before writing this, but the patches would have been out of context with 4.2.3.

**Comment by retokromer** [comment]
@dericed No problem! I actually had in mind that the patch was obsolete only in 4.3 and not in 4.2.3. (BTW: 4.3 should be released in 10 days or so.)

**Comment by dericed** [comment]
@retokromer, ah you're right in regards to the patch not in 4.2.3. If the next vrecord release is before the update of ffmpegdecklink.rb to 4.3, then I'll revert.

**Comment by retokromer** [comment]
I prefer to [revert](https://github.com/amiaopensource/homebrew-amiaos/pull/242), because also a few other people are using `ffmpegdecklink`.

**Pull request merged**
