### PR TITLE
delete dvrescue

### PR DESCRIPTION
**Pull request by retokromer**
Stable: version 0.19.11.20191114 is redundant with version scanned from URL

### CODE REVIEW

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
ping ping

**Comment by retokromer** [comment]
last ping

**Comment by privatezero** [comment]
Hi @retokromer - haven't been ignoring this, I just am not sure that this is the actual actively maintained formula for this tool. [Official docs](https://github.com/mipops/dvrescue) call for tapping `mediaarea/homebrew-mediaarea` to install, and I am not totally sure if this formula even needs to be maintained at AMIA-OS. Since nobody else has commented, maybe not?

**Comment by retokromer** [comment]
Hello @privatezero! This formula has actually be [added](https://github.com/amiaopensource/homebrew-amiaos/pull/226) here in our repository by @g-maxime, after having added it on [MediaArea](https://github.com/MediaArea/homebrew-mediaarea/commit/735d8582ecb098ac9f2ce0489f89ded1b3d95da7#diff-8f7c1c89401de7eb9cfade7fab748c8a).

**Comment by retokromer** [comment]
If that’s is okay also with @g-maxime, I’m fine with removing it here, but I’m not happy having here a formula which installs an old version of the software.

**Comment by privatezero** [comment]
I agree that installing the old version is not optimal! (Also having conflicting brew installs for those who have tapped both repositories is an issue). I'd say deletion is probably best if others are in agreement.

**Comment by kieranjol** [comment]
Aye, i think deletion is the way to go.

**Comment by retokromer** [comment]
@g-maxime @JeromeMartinez Qu’en dites-vous: j’efface de nouveau ici?

**Pull request merged**
